// <auto-generated />
using System;
using Maliev.FacilityService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.FacilityService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FacilityDbContext))]
    partial class FacilityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("asset_code");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ManufacturerSerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("manufacturer_serial_number");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("NextServiceDueDate")
                        .HasColumnType("date")
                        .HasColumnName("next_service_due_date");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<decimal?>("PurchasePriceTHB")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("purchase_price_thb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_category");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("WarrantyExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("warranty_expiry_date");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("equipments", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.EquipmentAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attachment_type");

                    b.Property<string>("ConditionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("condition_notes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("IsActive");

                    b.ToTable("equipment_attachments", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.EquipmentLoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_return_date");

                    b.Property<Guid?>("ApprovedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_employee_id");

                    b.Property<Guid>("BorrowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("borrower_id");

                    b.Property<string>("BorrowerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("borrower_type");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<DateOnly>("ExpectedReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_return_date");

                    b.Property<DateOnly>("LoanStartDate")
                        .HasColumnType("date")
                        .HasColumnName("loan_start_date");

                    b.Property<string>("LoanStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("loan_status");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("purpose");

                    b.Property<string>("ReturnConditionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("return_condition_notes");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("LoanStatus");

                    b.HasIndex("EquipmentId", "LoanStatus");

                    b.ToTable("equipment_loans", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.EquipmentMaintenanceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CostTHB")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost_thb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<Guid>("LoggedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("logged_by_employee_id");

                    b.Property<DateOnly?>("NextServiceDueDate")
                        .HasColumnType("date")
                        .HasColumnName("next_service_due_date");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vendor_name");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("equipment_maintenance_logs", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.EquipmentNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_employee_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EquipmentId", "CreatedAt");

                    b.ToTable("equipment_notes", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Infrastructure.Data.AssetCodeSequence", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<int>("LastSequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_sequence_number");

                    b.HasKey("Category");

                    b.ToTable("asset_code_sequences", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.GeneralEquipment", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.Equipment");

                    b.ToTable("GeneralEquipment");
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.Equipment");

                    b.Property<string>("ExtendedProperties")
                        .HasColumnType("text")
                        .HasColumnName("extended_properties");

                    b.Property<decimal>("HourlyRateTHB")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hourly_rate_thb");

                    b.Property<decimal>("SetupFeeTHB")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("setup_fee_thb");

                    b.ToTable("ManufacturingEquipment");
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.HandToolItem", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.GeneralEquipment");

                    b.ToTable("hand_tools", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.ITEquipmentItem", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.GeneralEquipment");

                    b.ToTable("it_equipment", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.MeasuringEquipmentItem", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.GeneralEquipment");

                    b.ToTable("measuring_equipment", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.OfficeEquipmentItem", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.GeneralEquipment");

                    b.ToTable("office_equipment", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.OtherEquipmentItem", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.GeneralEquipment");

                    b.ToTable("other_equipment", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.CncMachineEquipment", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment");

                    b.Property<string>("ControllerBrand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("controller_brand");

                    b.Property<decimal>("MaxSpindlePowerKw")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_spindle_power_kw");

                    b.Property<int>("MaxSpindleSpeedRpm")
                        .HasColumnType("integer")
                        .HasColumnName("max_spindle_speed_rpm");

                    b.Property<decimal>("MaxToolDiameterMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_tool_diameter_mm");

                    b.Property<int>("NumberOfAxes")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_axes");

                    b.Property<string>("ToolInterface")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tool_interface");

                    b.Property<decimal>("XTravelMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("x_travel_mm");

                    b.Property<decimal>("YTravelMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("y_travel_mm");

                    b.Property<decimal>("ZTravelMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("z_travel_mm");

                    b.ToTable("cnc_machine_specs", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.FdmPrinterEquipment", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment");

                    b.Property<decimal>("BuildVolumeXMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("build_volume_x_mm");

                    b.Property<decimal>("BuildVolumeYMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("build_volume_y_mm");

                    b.Property<decimal>("BuildVolumeZMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("build_volume_z_mm");

                    b.Property<decimal>("MaxLayerHeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_layer_height_mm");

                    b.Property<decimal>("MaxNozzleTempC")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_nozzle_temp_c");

                    b.Property<decimal>("MinLayerHeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("min_layer_height_mm");

                    b.Property<decimal>("NozzleDiameterMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("nozzle_diameter_mm");

                    b.Property<int>("NumberOfExtruders")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_extruders");

                    b.ToTable("fdm_printer_specs", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.InjectionMoldingEquipment", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment");

                    b.Property<int>("MaxInjectionPressureBar")
                        .HasColumnType("integer")
                        .HasColumnName("max_injection_pressure_bar");

                    b.Property<decimal>("MaxMoldXMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_mold_x_mm");

                    b.Property<decimal>("MaxMoldYMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_mold_y_mm");

                    b.Property<decimal>("MaxMoldZMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_mold_z_mm");

                    b.Property<decimal>("MaxShotSizeG")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_shot_size_g");

                    b.Property<int>("MaxTempC")
                        .HasColumnType("integer")
                        .HasColumnName("max_temp_c");

                    b.ToTable("injection_molding_specs", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.Scanner3DEquipment", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment");

                    b.Property<decimal>("AccuracyMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("accuracy_mm");

                    b.Property<decimal>("MaxScanVolumeM3")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("max_scan_volume_m3");

                    b.Property<string>("ScanResolutions")
                        .HasColumnType("text")
                        .HasColumnName("scan_resolutions");

                    b.Property<string>("ScannerTechnology")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scanner_technology");

                    b.ToTable("scanner_3d_specs", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.SlaPrinterEquipment", b =>
                {
                    b.HasBaseType("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment");

                    b.Property<decimal>("BuildVolumeXMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("build_volume_x_mm");

                    b.Property<decimal>("BuildVolumeYMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("build_volume_y_mm");

                    b.Property<decimal>("BuildVolumeZMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("build_volume_z_mm");

                    b.Property<string>("LightSourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("light_source_type");

                    b.Property<int>("WavelengthNm")
                        .HasColumnType("integer")
                        .HasColumnName("wavelength_nm");

                    b.Property<decimal>("XyResolutionMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("xy_resolution_mm");

                    b.ToTable("sla_printer_specs", (string)null);
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.EquipmentAttachment", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.EquipmentLoan", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.EquipmentMaintenanceLog", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.EquipmentNote", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.GeneralEquipment", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.Equipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.GeneralEquipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.Equipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.HandToolItem", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.GeneralEquipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.HandToolItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.ITEquipmentItem", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.GeneralEquipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.ITEquipmentItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.MeasuringEquipmentItem", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.GeneralEquipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.MeasuringEquipmentItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.OfficeEquipmentItem", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.GeneralEquipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.OfficeEquipmentItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.OtherEquipmentItem", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.GeneralEquipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.OtherEquipmentItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.CncMachineEquipment", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.CncMachineEquipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.FdmPrinterEquipment", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.FdmPrinterEquipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.InjectionMoldingEquipment", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.InjectionMoldingEquipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.Scanner3DEquipment", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.Scanner3DEquipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maliev.FacilityService.Domain.Entities.SlaPrinterEquipment", b =>
                {
                    b.HasOne("Maliev.FacilityService.Domain.Entities.ManufacturingEquipment", null)
                        .WithOne()
                        .HasForeignKey("Maliev.FacilityService.Domain.Entities.SlaPrinterEquipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
