namespace Maliev.FacilityService.Application.Interfaces;

/// <summary>
/// Abstraction for publishing domain events to the messaging infrastructure.
/// Implemented by Infrastructure layer using MassTransit.
/// </summary>
public interface IEventPublisher
{
    /// <summary>
    /// Publishes an event indicating that an equipment's status has changed.
    /// </summary>
    /// <param name="equipmentId">The ID of the equipment whose status changed.</param>
    /// <param name="assetCode">The asset code of the equipment.</param>
    /// <param name="name">The display name of the equipment.</param>
    /// <param name="category">The category of the equipment as a string.</param>
    /// <param name="previousStatus">The previous status as a string.</param>
    /// <param name="newStatus">The new status as a string.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A task representing the asynchronous publish operation.</returns>
    Task PublishEquipmentStatusChangedAsync(
        Guid equipmentId,
        string assetCode,
        string name,
        string category,
        string previousStatus,
        string newStatus,
        CancellationToken ct = default);

    /// <summary>
    /// Publishes an event requesting a loan document to be generated by PdfService.
    /// </summary>
    /// <param name="loanId">The ID of the approved loan.</param>
    /// <param name="equipmentId">The ID of the loaned equipment.</param>
    /// <param name="assetCode">The asset code of the loaned equipment.</param>
    /// <param name="equipmentName">The display name of the loaned equipment.</param>
    /// <param name="brand">The brand of the loaned equipment.</param>
    /// <param name="modelName">The model name of the loaned equipment.</param>
    /// <param name="manufacturerSerial">The manufacturer serial number of the loaned equipment.</param>
    /// <param name="borrowerId">The ID of the borrower.</param>
    /// <param name="borrowerName">The display name of the borrower.</param>
    /// <param name="borrowerType">The type of borrower (Employee or Customer).</param>
    /// <param name="approvedByEmployeeId">The ID of the employee who approved the loan.</param>
    /// <param name="loanStartDate">The start date of the loan.</param>
    /// <param name="expectedReturnDate">The expected return date of the loan.</param>
    /// <param name="purpose">The stated purpose of the loan.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A task representing the asynchronous publish operation.</returns>
    Task PublishLoanDocumentRequestedAsync(
        Guid loanId,
        Guid equipmentId,
        string assetCode,
        string equipmentName,
        string? brand,
        string? modelName,
        string? manufacturerSerial,
        Guid borrowerId,
        string borrowerName,
        string borrowerType,
        Guid approvedByEmployeeId,
        DateOnly loanStartDate,
        DateOnly expectedReturnDate,
        string purpose,
        CancellationToken ct = default);
}
