<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Maliev.FacilityService.Application\Maliev.FacilityService.Application.csproj" />
    <ProjectReference Include="..\Maliev.FacilityService.Domain\Maliev.FacilityService.Domain.csproj" />
    <ProjectReference Include="..\..\Maliev.MessagingContracts\generated\csharp\Maliev.MessagingContracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.7" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
